config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :pet_histories
  resources :pets

  root 'clients#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_many :pet_histories
    belongs_to :client
  
        def visit_counter
            pet_histories.count
        end

        def avg_wt
            self.pet_histories.average(:weight)
        end

        def avg_ht
            self.pet_histories.average(:height)
        end


        def max_wt
            self.pet_histories.maximum(:weight)
        end


        def max_ht
            self.pet_histories.maximum(:height)
        end

end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
  belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: [:show, :edit, :update, :destroy]

  # GET /pet_histories
  # GET /pet_histories.json
  def index
    @pet_histories = PetHistory.all
    if !params[:pet_id].blank?
      @pet_histories = @pet_histories.where(pet_id: params[:pet_id])
      @pet = Pet.find(params[:pet_id])
    end
  end

  # GET /pet_histories/1
  # GET /pet_histories/1.json
  def show
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
    @pets = Pet.all.order(name: 'asc')
  end

  # GET /pet_histories/1/edit
  def edit
    @pets = Pet.all.order(name: 'asc')
  end

  # POST /pet_histories
  # POST /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully created.' }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1
  # PATCH/PUT /pet_histories/1.json
  def update
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to @pet_history, notice: 'Pet history was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_history }
      else
        format.html { render :edit }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1
  # DELETE /pet_histories/1.json
  def destroy
    @pet_history.destroy
    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: 'Pet history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_history_params
      params.require(:pet_history).permit(:pet_id, :condition, :diagnostic, :height, :weight)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    @clients = Client.all.order(name: 'desc')
  end

  # GET /pets/1/edit
  def edit
    @clients = Client.all.order(name: 'desc')
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :birthday, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.html.erb
<div class="container">

<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Telefono %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Mascotas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= client.pets.count %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clients/new.html.erb
<h1 class="text-center">Nuevo cliente</h1>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<h3>Mascotas</h3>

<table class="table">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Altura maxima (en cm)</th>
    <th>Peso Maximo (en kg)</th>
  </tr>
  </thead>
  <tbody>
  <% @client.pets.each do |pet| %>
    <tr>
      <td><%= pet.name %></td>
      <td><%= pet.max_ht %></td>
      <td><%= pet.max_wt %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  </head>

  <body>
    <%= render "partials/navbar" %>
    <%= yield %>
  </body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to "Registrar cliente", new_client_path , class:"nav-link" %>  

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Registrar mascota", new_pet_path , class:"nav-link" %> 
      </li>
      <li class="nav-item">
        <%= link_to "Visita Medica", new_pet_history_path , class:"nav-link" %> 
      </li>
      <li class="nav-item">
        <%= link_to "clientes", clients_path , class:"nav-link" %> 
      </li>
      <li class="nav-item">
        <%= link_to "mascotas", pets_path , class:"nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/pet_histories/_form.html.erb
<div class="container">
<%= form_with(model: pet_history, local: true) do |form| %>
  <% if pet_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

      <ul>
        <% pet_history.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Mascota %>
    <%= form.select :pet_id, options_from_collection_for_select(@pets, 'id', 'name', pet_history.pet_id) %>
  </div>

  <div class="field">
    <%= form.label :Condicion %>
    <%= form.text_field :condition %>
  </div>

  <div class="field">
    <%= form.label :Diagnostico %>
    <%= form.text_field :diagnostic %>
  </div>

  <div class="field">
    <%= form.label :Tamaño, 'Tamaño (en cm)' %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :Peso, 'Peso (en kg)' %>
    <%= form.number_field :weight %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  </div>

app/views/pet_histories/edit.html.erb
<h1>Editing Pet History</h1>

<%= render 'form', pet_history: @pet_history %>

<%= link_to 'Show', @pet_history %> |
<%= link_to 'Back', pet_histories_path %>

app/views/pet_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visitas Medicas <%= !params[:pet_id].blank? ? "(#{@pet.name})" : "" %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Mascota</th>
      <th>Condicion</th>
      <th>Diagnostico</th>
      <th>Altura (en cm)</th>
      <th>Peso (en kg)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pet_histories.each do |pet_history| %>
      <tr>
        <td><%= pet_history.pet.name %></td>
        <td><%= pet_history.condition %></td>
        <td><%= pet_history.diagnostic %></td>
        <td><%= pet_history.height %></td>
        <td><%= pet_history.weight %></td>
        <td><%= link_to 'Show', pet_history %></td>
        <td><%= link_to 'Edit', edit_pet_history_path(pet_history) %></td>
        <td><%= link_to 'Destroy', pet_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet History', new_pet_history_path %> |
<%= link_to 'Pets', pets_path %> |
<%= link_to 'Clients', clients_path %>

app/views/pet_histories/new.html.erb
<h1 class="text-center">Nueva visita Medica</h1>

<%= render 'form', pet_history: @pet_history %>

app/views/pet_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mascota:</strong>
  <%= @pet_history.pet.name %>
</p>

<p>
  <strong>Condicion:</strong>
  <%= @pet_history.condition %>
</p>

<p>
  <strong>Diagnostico:</strong>
  <%= @pet_history.diagnostic %>
</p>

<p>
  <strong>Altura (en cm):</strong>
  <%= @pet_history.height %>
</p>

<p>
  <strong>peso (en kg):</strong>
  <%= @pet_history.weight %>
</p>

app/views/pets/_form.html.erb
<div class="container">
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Raza %>
    <%= form.text_field :breed %>
  </div>

  <div class="field">
    <%= form.label :birthday, "Fecha de nacimiento" %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :Dueño %>
    <%= form.select :client_id, options_from_collection_for_select(@clients, 'id', 'name', pet.client_id) %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
  </div>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Raza</th>
      <th>Fecha de nacimiento</th>
      <th>Total de visitas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.birthday.strftime('%d/%m/%Y') %></td>
        <td><%= pet.visit_counter %></td>
        <td><%= link_to 'History', pet_histories_url(pet_id: pet.id) %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pets/new.html.erb
<h1 class="text-center">Nueva Mascota</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Raza:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @pet.birthday.strftime('%d/%m/%Y') %>
</p>

<p>
  <strong>Altura promedio:</strong>
  <%= @pet.avg_ht %>
</p>

<p>
  <strong>Peso promedio:</strong>
  <%= @pet.avg_wt %>
</p>

<p>
  <strong>Altura maxima:</strong>
  <%= @pet.max_ht %>
</p>

<p>
  <strong>Peso maximo:</strong>
  <%= @pet.max_wt %>
</p>

<h3>History</h3>

<table class="table">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Altura (en cm)</th>
      <th>Peso (en kg)</th>
    </tr>
  </thead>
  <tbody>
    <% @pet.pet_histories.each do |history| %>
    <tr>
      <td><%= history.created_at.strftime('%d/%m/%Y') %></td>
      <td><%= history.height %></td>
      <td><%= history.weight %></td>
    </tr>
    <% end %>
  </tbody>
</table>